import { FormControl } from '@angular/forms';
import { QuestionModel } from '../models/question.model';

export const questions: QuestionModel[] = [
  new QuestionModel({
    step: 0,
    question: 'question1',
    answer: new FormControl('family'),
    required: true,
    nextStep: 0.1,
  }),
  new QuestionModel({
    step: 0.1,
    question: 'question2',
    answer: new FormControl('spain'),
    required: true,
    nextStep: 1,
  }),
  new QuestionModel({
    step: 1,
    question: 'question3',
    answer: new FormControl(0),
    required: true,
    nextStep: 2,
  }),
  new QuestionModel({
    step: 2,
    question: 'question4',
    answer: new FormControl(0),
    required: true,
    nextStep: 3,
  }),
  new QuestionModel({
    step: 3,
    question: 'question5',
    answer: new FormControl('flight'),
    required: true,
    nextStep: 3.1,
  }),
  new QuestionModel({
    step: 3.1,
    question: 'question6',

    answer: new FormControl('vtc'),
    required: true,
    nextStep: 3.2,
  }),
  new QuestionModel({
    step: 4,
    question: 'question7',
    answer: new FormControl('airbnb'),
    required: true,
    nextStep: 4.1,
  }),
  new QuestionModel({
    step: 4.1,
    question: 'question8',
    answer: new FormControl('high'),
    required: true,
    nextStep: 4.3,
  }),
  new QuestionModel({
    step: 4.2,
    question: 'question9',

    answer: new FormControl(true),
    required: true,
    nextStep: 4.3,
  }),
  new QuestionModel({
    step: 4.3,
    question: 'question10',
    answer: new FormControl(true),
    required: true,
    nextStep: 5,
  }),
  new QuestionModel({
    step: 5,
    question: 'question11',
    answer: new FormControl(true),
    required: true,
    nextStep: 6,
  }),
  new QuestionModel({
    step: 6,
    question: 'question12',
    answer: new FormControl(true),
    required: true,
    nextStep: 6.1,
  }),
  new QuestionModel({
    step: 6.1,
    question: 'question13',
    answer: new FormControl(true),
    required: true,
    nextStep: 7,
  }),
  new QuestionModel({
    step: 7,
    question: 'question14',
    answer: new FormControl(1),
    required: true,
    nextStep: 8,
  }),
  new QuestionModel({
    step: 8,
    question: 'question15',
    answer: new FormControl(new Date()),
    required: true,
    nextStep: 9,
  }),
  new QuestionModel({
    step: 9,
    question: 'question16',
    answer: new FormControl(new Date()),
    required: true,
    nextStep: 10,
  }),
  new QuestionModel({
    step: 10,
    question: 'question17',
    answer: new FormControl('usa'),
    required: true,
    nextStep: null,
  }),
];
