import { FormControl } from '@angular/forms';
import { QuestionModel } from '../models/question.model';
import {
  BundleOptions,
  CityTransportationOptions,
  CurrencyOptions,
  DestinationOptions,
  FoodOptions,
  HotelOptions,
  LodgeOptions,
  OriginOptions,
  PlaceOptions,
  TransportationOptions,
  YesOrNoOptions,
} from './answer-options.config';

export const questions: QuestionModel[] = [
  new QuestionModel({
    step: 0,
    question: 'question1',
    answer: new FormControl('romantic'),
    required: true,
    previousStep: null,
    nextStep: 1,
    information: '',
    errorMessage: 'questions.question1_error',
    options: BundleOptions,
  }),
  new QuestionModel({
    step: 1,
    question: 'question2',
    answer: new FormControl('spain'),
    required: true,
    previousStep: 0,
    nextStep: 2,
    information: '',
    options: DestinationOptions,
    errorMessage: 'questions.question2_error',
  }),
  new QuestionModel({
    step: 2,
    question: 'question3',
    answer: new FormControl(1),
    required: true,
    previousStep: 1,
    nextStep: 3,
    information: '',
    errorMessage: 'questions.question3_error',
  }),
  new QuestionModel({
    step: 3,
    question: 'question4',
    answer: new FormControl(1),
    required: false,
    previousStep: 2,
    nextStep: 4,
    information: '',
    errorMessage: 'questions.question4_error',
  }),
  new QuestionModel({
    step: 4,
    question: 'question5',
    answer: new FormControl('flight'),
    required: true,
    previousStep: 3,
    nextStep: 5,
    information: '',
    errorMessage: 'questions.question5_error',

    options: TransportationOptions,
  }),
  new QuestionModel({
    step: 5,
    question: 'question6',
    answer: new FormControl('vtc'),
    required: true,
    previousStep: 4,
    nextStep: 6,
    information: '',
    errorMessage: 'questions.question6_error',

    options: CityTransportationOptions,
  }),
  new QuestionModel({
    step: 6,
    question: 'question7',
    answer: new FormControl('hotel'),
    required: true,
    previousStep: 5,

    nextStep: 7,
    information: '',
    errorMessage: 'questions.question7_error',
    options: LodgeOptions,
  }),
  new QuestionModel({
    step: 7,
    question: 'question8',
    answer: new FormControl('medium'),
    required: true,
    previousStep: 6,
    nextStep: 9,
    information: '',
    errorMessage: 'questions.question8_error',
    options: HotelOptions,
  }),
  new QuestionModel({
    step: 8,
    question: 'question9',
    answer: new FormControl('groceries'),
    required: true,
    previousStep: 7,
    nextStep: 9,
    information: '',
    errorMessage: 'questions.question9_error',

    options: FoodOptions,
  }),
  new QuestionModel({
    step: 9,
    question: 'question10',
    answer: new FormControl(true),
    required: true,
    previousStep: 8,
    nextStep: 10,
    information: '',
    errorMessage: 'questions.question10_error',
    options: YesOrNoOptions,
  }),
  new QuestionModel({
    step: 10,
    question: 'question11',
    answer: new FormControl('city'),
    required: true,
    previousStep: 9,

    nextStep: 11,
    information: '',
    errorMessage: 'questions.question11_error',

    options: PlaceOptions,
  }),
  new QuestionModel({
    step: 11,
    question: 'question12',
    answer: new FormControl(true),
    required: true,
    previousStep: 10,

    nextStep: 12,
    information: '',
    errorMessage: 'questions.question12_error',

    options: YesOrNoOptions,
  }),
  new QuestionModel({
    step: 12,
    question: 'question13',
    answer: new FormControl(true),
    required: true,
    nextStep: 13,
    previousStep: 11,

    information: '',
    errorMessage: 'questions.question13_error',

    options: YesOrNoOptions,
  }),
  new QuestionModel({
    step: 13,
    question: 'question14',
    answer: new FormControl(8),
    required: true,
    previousStep: 12,

    nextStep: 14,
    information: '',
    errorMessage: 'questions.question14_error',
  }),
  new QuestionModel({
    step: 14,
    question: 'question15',
    answer: new FormControl(new Date()),
    required: true,
    previousStep: 13,

    nextStep: 15,
    information: '',
    errorMessage: 'questions.question15_error',
  }),
  new QuestionModel({
    step: 15,
    question: 'question16',
    answer: new FormControl('usa'),
    required: true,
    previousStep: 14,

    nextStep: 16,
    information: '',
    errorMessage: 'questions.question16_error',
    options: OriginOptions,
  }),
  new QuestionModel({
    step: 16,
    question: 'question17',
    answer: new FormControl('pol'),
    required: true,
    previousStep: 15,

    nextStep: 17,
    information: '',
    errorMessage: 'questions.question17_error',
  }),
  new QuestionModel({
    step: 17,
    question: 'question18',
    answer: new FormControl('pa@a.com'),
    required: true,
    previousStep: 16,
    nextStep: 18,
    information: '',
    errorMessage: 'questions.question18_error',
  }),
  new QuestionModel({
    step: 18,
    question: 'question19',
    answer: new FormControl('euros'),
    required: true,
    previousStep: 17,
    nextStep: null,
    information: '',
    errorMessage: 'questions.question19_error',
    options: CurrencyOptions,
  }),
];
